UniversityProject/UniversityProject/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using UniversityProject.ViewModel;

namespace UniversityProject.Models
{
    public class Student
    {
        public int StudentId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public int CNP { get; set; }

        public int Age { get; set; }

        public int? CollegeId { get; set; }

        [NotMapped]
        public List<Grade> Grades { get; set; }

        [NotMapped]
        public List<College> RequestedColleges { get; set; }

        [NotMapped]
        public List<StudentGradeViewModel> StudentGrade { get; set; }
   

    }
}

UniversityProject/UniversityProject/Controllers/DistributionController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using UniversityProject.Models;
using UniversityProject.Repositories;
using UniversityProject.Services;
using UniversityProject.ViewModel;

namespace UniversityProject.Controllers
{
    public class DistributionController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        private readonly IStudentDistributionService StudentDistributionService;

        public DistributionController(IUnitOfWork unitOfWork,IStudentDistributionService StudentDistributionService)
        {


            this.StudentDistributionService = StudentDistributionService;

            this.unitOfWork = unitOfWork;

        }



        public IActionResult Index()
        {

            List<Student> students = StudentDistributionService.GetStudents();

            List<StudentGradeViewModel> StudentGradeList = new List<StudentGradeViewModel>();

            Dictionary<int, List<StudentGradeViewModel>> colStud = new Dictionary<int, List<StudentGradeViewModel>>();

            List<StudentGradeViewModel> unassignedStudents = new List<StudentGradeViewModel>();

            Dictionary<int, List<StudentGradeViewModel>> orderedDict = new Dictionary<int, List<StudentGradeViewModel>>();

            List<StudentGradeViewModel> FinalList = new List<StudentGradeViewModel>();

            //fills the student lists, studentgradelist and dictionary colStud
            StudentDistributionService.GenerateStudentGrades(students, StudentGradeList, colStud);


            //ordered dict contains the grades of the students ordered
            orderedDict = StudentDistributionService.OrderDictionaryByGrade(colStud);

            //gets a list of students which have not been accepted to any college yet
            unassignedStudents = StudentDistributionService.GetUnassignedStudents(orderedDict);


            StudentDistributionService.AssignUnassignedStudents(unassignedStudents, students, orderedDict);



            FinalList = StudentDistributionService.GetAssignedStudents(orderedDict, students);


            ViewBag.FinalList = FinalList;

            if(students.Count != 0)
            {
                return View(students.First());
            }else
            {
                return View();
            }

            
        }
    }
}

UniversityProject/UniversityProject/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityProject.Models;
using UniversityProject.Repositories;

namespace UniversityProject.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public StudentsController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        // GET: Students
        public IActionResult Index()
        {

            return View(unitOfWork.StudentRepository.GetAll());

        }

        // GET: Students/Details/5
        public IActionResult Details(int? id)
        {
            
            Student student = unitOfWork.StudentRepository
                .GetFirstOrDefault(m => m.StudentId == id);

            

            return View(student);
        }

     
    }
}

UniversityProject/UniversityProject/Views/Students/Details.cshtml
@model UniversityProject.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CNP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CNP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

UniversityProject/UniversityProject/Views/Students/Index.cshtml
@model IEnumerable<UniversityProject.Models.Student>

@{
    ViewData["Title"] = "Students List";
}

    <h1>Students List</h1>

<p>
    <button type="button" class="btn btn-success" value="redirect" onclick="window.location='@Url.Action("Index", "Distribution")'">Show Assigned Students</button>
</p>



<table class="table table-striped">
    <thead>
        <tr class="table-warning">
            <th >
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CNP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CNP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
               
                <a asp-action="Details" asp-route-id="@item.StudentId">Details</a> 
              
            </td>
        </tr>
}
    </tbody>
</table>